server:
  port: 9000
  read_timeout: 30
  write_timeout: 30
  idle_timeout: 30

database:
  driver: mongodb
  uri: mongodb://template:template@localhost:27017/?authSource=beta
  name: beta
  
log:
  level: info
  text_logging: false